Financeiro/src/main/java/br/teste/pojo/Lancamento.java
package br.teste.pojo;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import br.teste.enums.TipoLancamento;

@Entity
@Table(name = "lancamento")
public class Lancamento {
	private Long id;
	private Pessoa pessoa;
	private String descricao;
	private BigDecimal valor;
	private TipoLancamento tipo;
	private Date dataVencimento;
	private Date dataPagamento;

	@Id
	@GeneratedValue
	public Long getId() {
		return id;
	}

	@NotNull
	@ManyToOne(optional = false)
	@JoinColumn(name = "pessoa_id")
	public Pessoa getPessoa() {
		return pessoa;
	}

	@NotEmpty
	@Size(max = 80)
	@Column(length = 80, nullable = false)
	public String getDescricao() {
		return descricao;
	}

	@NotNull
	@DecimalMin("0")
	@Column(precision = 10, scale = 2, nullable = false)
	public BigDecimal getValor() {
		return valor;
	}

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false)
	public TipoLancamento getTipo() {
		return tipo;
	}

	@NotNull
	@Temporal(TemporalType.DATE)
	@Column(name = "data_vencimento", nullable = false)
	public Date getDataVencimento() {
		return dataVencimento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_pagamento", nullable = true)
	public Date getDataPagamento() {
		return dataPagamento;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public void setTipo(TipoLancamento tipo) {
		this.tipo = tipo;
	}

	public void setDataVencimento(Date dataVencimento) {
		this.dataVencimento = dataVencimento;
	}

	public void setDataPagamento(Date dataPagamento) {
		this.dataPagamento = dataPagamento;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Lancamento other = (Lancamento) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
}

Financeiro/src/main/java/br/teste/pojo/Pessoa.java
package br.teste.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Table(name = "pessoa")
public class Pessoa {

	private Long id;
	private String nome;

	public void setId(Long id) {
		this.id = id;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}
	
	@Id
	@GeneratedValue
	public Long getId() {
	return id;
	}
	@NotEmpty
	@Size(max = 60)
	@Column(length = 60, nullable = false)
	public String getNome() {
	return nome;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pessoa other = (Pessoa) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}

Financeiro/src/main/java/br/teste/mb/CadastroLancamentoBean.java
package br.teste.mb;

import java.io.Serializable;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;

import br.teste.enums.TipoLancamento;
import br.teste.exceptions.NegocioException;
import br.teste.pojo.Lancamento;
import br.teste.pojo.Pessoa;
import br.teste.repository.Lancamentos;
import br.teste.repository.Pessoas;
import br.teste.rules.CadastroLancamentos;
import br.teste.util.JpaUtil;

@ManagedBean
@ViewScoped
public class CadastroLancamentoBean implements Serializable {
	private static final long serialVersionUID = 1L;
	private Lancamento lancamento = new Lancamento();
	private List<Pessoa> todasPessoas;

	public void prepararCadastro() {
		EntityManager manager = JpaUtil.getEntityManager();
		try {
			Pessoas pessoas = new Pessoas(manager);
			this.todasPessoas = pessoas.todas();
		} finally {
			manager.close();
		}
	}

	public void salvar() {
		EntityManager manager = JpaUtil.getEntityManager();
		EntityTransaction trx = manager.getTransaction();
		FacesContext context = FacesContext.getCurrentInstance();
		try {
			trx.begin();
			CadastroLancamentos cadastro = new CadastroLancamentos(
					new Lancamentos(manager));
			cadastro.salvar(this.lancamento);
			this.lancamento = new Lancamento();
			context.addMessage(null, new FacesMessage(
					"Lançamento salvo com sucesso!"));
			trx.commit();
		} catch (NegocioException e) {
			trx.rollback();
			FacesMessage mensagem = new FacesMessage(e.getMessage());
			mensagem.setSeverity(FacesMessage.SEVERITY_ERROR);
			context.addMessage(null, mensagem);
		} finally {
			manager.close();
		}
	}

	public List<Pessoa> getTodasPessoas() {
		return this.todasPessoas;
	}

	public TipoLancamento[] getTiposLancamentos() {
		return TipoLancamento.values();
	}

	public Lancamento getLancamento() {
		return lancamento;
	}

	public void setLancamento(Lancamento lancamento) {
		this.lancamento = lancamento;
	}
}

Financeiro/src/main/java/br/teste/mb/ConsultaLancamentosBean.java
package br.teste.mb;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.persistence.EntityManager;

import br.teste.pojo.Lancamento;
import br.teste.repository.Lancamentos;
import br.teste.util.JpaUtil;

@ManagedBean
@ViewScoped
public class ConsultaLancamentosBean {
	private List<Lancamento> lancamentos;

	public void consultar() {
		EntityManager manager = JpaUtil.getEntityManager();
		Lancamentos lancamentos = new Lancamentos(manager);
		this.lancamentos = lancamentos.todos();
		manager.close();
	}

	public List<Lancamento> getLancamentos() {
		return lancamentos;
	}
}

Financeiro/src/main/java/br/teste/mb/NomesBean.java
package br.teste.mb;

import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.component.html.HtmlCommandButton;
import javax.faces.component.html.HtmlInputText;

//@RequestScoped // existe apenas em caso de request e é apagado a uma nova requisição
//@ViewScoped // existe apenas quando a página estiver sendo exisbida, quando mudar de página ou recarregar será apagado
//@SessionScoped // existe durante a sessão do usuário, mesmo que ele saia da página, compartilha apenas uma instância do MB com cada usuário.
@ApplicationScoped // existe enquanto a aplicação estiver sendo carregada, compartilhando a mesma instância do MB com todos os usuário.
@ManagedBean
public class NomesBean {
	private String nome;
	private List<String> nomes = new ArrayList<>();

	private HtmlInputText inputNome;
	public HtmlInputText getInputNome() {
		return inputNome;
	}

	public HtmlCommandButton getBotaoAdicionar() {
		return botaoAdicionar;
	}

	public void setNomes(List<String> nomes) {
		this.nomes = nomes;
	}

	public void setInputNome(HtmlInputText inputNome) {
		this.inputNome = inputNome;
	}

	public void setBotaoAdicionar(HtmlCommandButton botaoAdicionar) {
		this.botaoAdicionar = botaoAdicionar;
	}

	private HtmlCommandButton botaoAdicionar;

	public void adicionar() {
		this.nomes.add(nome);
		// desativa campo e botão quando mais que 3 nomes
		// forem adicionados
		if (this.nomes.size() > 3) {
			this.inputNome.setDisabled(true);
			this.botaoAdicionar.setDisabled(true);
			this.botaoAdicionar.setValue("Muitos nomes adicionados...");
		}
	}
	
	public String chameOla() {
		if(nomes.isEmpty())
			return null;
		return "Ola"; 

	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public List<String> getNomes() {
		return nomes;
	}
}

Financeiro/src/main/java/br/teste/mb/OlaBean.java
package br.teste.mb;

import javax.faces.bean.ManagedBean;

@ManagedBean(name = "ola")
public class OlaBean {

	private String nome;
	private String sobrenome;
	private String nomeCompleto;

	public void dizerOla() {
		this.nomeCompleto = this.nome.toUpperCase() + " " + this.sobrenome;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getSobrenome() {
		return sobrenome;
	}

	public void setSobrenome(String sobrenome) {
		this.sobrenome = sobrenome;
	}

	public String getNomeCompleto() {
		return nomeCompleto;
	}

	public void setNomeCompleto(String nomeCompleto) {
		this.nomeCompleto = nomeCompleto;
	}

}

Financeiro/src/main/webapp/CadastroLancamento.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/template/Layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
	<f:metadata>
		<f:viewAction action="#{cadastroLancamentoBean.prepararCadastro}" />
	</f:metadata>
	<ui:define name="titulo">Cadastro de lançamento</ui:define>
	<ui:define name="corpo">
		<h1>Cadastro de lançamento</h1>
		<h:form id="frm">
			<h:messages showDetail="false" showSummary="true" />
			<h:panelGrid columns="2">
				<h:outputLabel value="Tipo" />
				<h:selectOneRadio value="#{cadastroLancamentoBean.lancamento.tipo}"
					label="Tipo do lançamento">
					<f:selectItems value="#{cadastroLancamentoBean.tiposLancamentos}"
						var="tipoLancamento" itemValue="#{tipoLancamento}" />
				</h:selectOneRadio>
				<h:outputLabel value="Pessoa" />
				<h:selectOneMenu value="#{cadastroLancamentoBean.lancamento.pessoa}"
					label="Pessoa">
					<f:selectItem itemLabel="Selecione" noSelectionOption="true" />
					<f:selectItems value="#{cadastroLancamentoBean.todasPessoas}"
						var="pessoa" itemValue="#{pessoa}" itemLabel="#{pessoa.nome}" />
				</h:selectOneMenu>
				<h:outputLabel value="Descrição" />
				<h:inputText size="60"
					value="#{cadastroLancamentoBean.lancamento.descricao}"
					label="Descrição" />
				<h:outputLabel value="Valor" />
				<h:inputText size="12"
					value="#{cadastroLancamentoBean.lancamento.valor}" label="Valor">
					<f:convertNumber locale="pt_BR" maxFractionDigits="2"
						minFractionDigits="2" />
				</h:inputText>
				<h:outputLabel value="Data de vencimento" />
				<h:inputText size="12"
					value="#{cadastroLancamentoBean.lancamento
.dataVencimento}"
					label="Data de vencimento">
					<f:convertDateTime pattern="dd/MM/yyyy"
						timeZone="America/Sao_Paulo" />
				</h:inputText>
				<h:outputLabel value="Data de pagamento" />
				<h:inputText size="12"
					value="#{cadastroLancamentoBean.lancamento
.dataPagamento}"
					label="Data de pagamento">
					<f:convertDateTime pattern="dd/MM/yyyy"
						timeZone="America/Sao_Paulo" />
				</h:inputText>
				<h:outputLabel />
				<h:commandButton value="Salvar"
					action="#{cadastroLancamentoBean.salvar}" />
			</h:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>

Financeiro/src/main/webapp/ConsultaLancamentos.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/template/Layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
	<f:metadata>
		<f:viewAction action="#{consultaLancamentosBean.consultar}" />
	</f:metadata>
	<ui:define name="titulo">Consulta de lançamentos</ui:define>
	<ui:define name="corpo">
		<h1>Consulta de lançamentos</h1>
		<h:form id="frm">
			<h:dataTable value="#{consultaLancamentosBean.lancamentos}"
				var="lancamento" border="1" cellspacing="0" cellpadding="2">
				<h:column>
					<f:facet name="header">
						<h:outputText value="Pessoa" />
					</f:facet>
					<h:outputText value="#{lancamento.pessoa.nome}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Descrição" />
					</f:facet>
					<h:outputText value="#{lancamento.descricao}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Tipo" />
					</f:facet>
					<h:outputText value="#{lancamento.tipo}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Valor" />
					</f:facet>
					<h:outputText value="#{lancamento.valor}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Data de vencimento" />
					</f:facet>
					<h:outputText value="#{lancamento.dataVencimento}" />
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Data de pagamento" />
					</f:facet>
					<h:outputText value="#{lancamento.dataPagamento}" />
				</h:column>
			</h:dataTable>
		</h:form>
	</ui:define>
</ui:composition>

Financeiro/src/main/webapp/Nomes.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:composite="http://xmlns.jcp.org/jsf/composite">
<h:head>
	<title>Lista de nomes</title>
</h:head>
<h:body>
	<h:form>
		<!-- binding entre compoentes se dá por propriedade binding -->
		Nome: <h:inputText value="#{nomesBean.nome}"
			binding="#{nomesBean.inputNome}" />
		<br />
		<h:commandButton value="Adicionar" action="#{nomesBean.adicionar}"
			binding="#{nomesBean.botaoAdicionar}" />
		<h:commandButton value="Adicionar" action="#{nomesBean.chameOla}" />
		<br />
		<ol>
			<ui:repeat var="nome" value="#{nomesBean.nomes}">
				<li>#{nome}</li>
			</ui:repeat>
		</ol>
	</h:form>
</h:body>
</html>

Financeiro/src/main/webapp/Ola.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html">
<h:head>
	<title>Olá JSF</title>
</h:head>
<h:body>
	<h:form>
		<h1>Olá #{ola.nomeCompleto}</h1>
		Nome: <h:inputText value="#{ola.nome}"/>
		<br />
		Sobrenome: <h:inputText value="#{ola.sobrenome}"/>
		<br />
		<h:commandButton value="Dizer olá" action="#{ola.dizerOla}" />
	</h:form>
</h:body>
</html>